/*
 * @version   : 2.5.0 - Ext.NET Pro License
 * @author    : Ext.NET, Inc. http://www.ext.net/
 * @date      : 2014-03-04
 * @copyright : Copyright (c) 2008-2014, Ext.NET, Inc. (http://www.ext.net/). All rights reserved.
 * @license   : See license.txt and http://www.ext.net/license/. 
 * @website   : http://www.ext.net/
 */


Ext.define('Ext.ux.statusbar.StatusBar',{extend:'Ext.toolbar.Toolbar',alternateClassName:'Ext.ux.StatusBar',alias:'widget.statusbar',requires:['Ext.toolbar.TextItem'],cls:'x-statusbar',busyIconCls:'x-status-busy',busyText:'Loading...',autoClear:5000,emptyText:'&nbsp;',activeThreadId:0,initComponent:function(){var right=this.statusAlign==='right';this.callParent(arguments);this.currIconCls=this.iconCls||this.defaultIconCls;this.statusEl=Ext.create('Ext.toolbar.TextItem',{cls:'x-status-text '+(this.currIconCls||''),text:this.text||this.defaultText||''});if(right){this.cls+=' x-status-right';this.add('->');this.add(this.statusEl);}else{this.insert(0,this.statusEl);this.insert(1,'->');}},setStatus:function(o){if(!this.statusEl.rendered){this.statusEl.on("render",function(){this.setStatus(o);},this);return this;}
o=o||{};Ext.suspendLayouts();if(Ext.isString(o)){o={text:o};}
if(o.text!==undefined){this.setText(o.text);}
if(o.iconCls!==undefined){this.setIcon(o.iconCls);}
else if(o.clearIcon==true){this.setIcon("");}
if(o.clear){var c=o.clear,wait=this.autoClear,defaults={useDefaults:true,anim:true};if(Ext.isObject(c)){c=Ext.applyIf(c,defaults);if(c.wait){wait=c.wait;}}else if(Ext.isNumber(c)){wait=c;c=defaults;}else if(Ext.isBoolean(c)){c=defaults;}
c.threadId=this.activeThreadId;Ext.defer(this.clearStatus,wait,this,[c]);}
Ext.resumeLayouts(true);return this;},clearStatus:function(o){if(!this.statusEl.rendered){this.statusEl.on("render",function(){this.clearStatus(o);},this);return this;}
o=o||{};if(o.threadId&&o.threadId!==this.activeThreadId){return this;}
var text=o.useDefaults?this.defaultText:this.emptyText,iconCls=o.useDefaults?(this.defaultIconCls?this.defaultIconCls:''):'';if(o.anim){this.statusEl.el.puff({remove:false,useDisplay:true,scope:this,callback:function(){this.statusEl.el.show();this.setStatus({text:text,iconCls:iconCls});}});}else{this.setStatus({text:text,iconCls:iconCls});}
return this;},setText:function(text){this.activeThreadId++;this.text=text||'';if(this.rendered){this.statusEl.setText(this.text);}
return this;},getText:function(){return this.text;},setIcon:function(cls){this.activeThreadId++;cls=cls||'';if(this.rendered){if(this.currIconCls){this.statusEl.removeCls("x-status-busy-base");this.statusEl.removeCls(this.currIconCls.split(" "));this.currIconCls=null;}
if(cls.length>0){this.statusEl.addCls("x-status-busy-base "+cls);this.currIconCls=cls;}}else{this.currIconCls=cls;}
return this;},showBusy:function(o){if(Ext.isString(o)){o={text:o};}
o=Ext.applyIf(o||{},{text:this.busyText,iconCls:this.busyIconCls});return this.setStatus(o);}});Ext.define('Ext.ux.statusbar.ValidationStatus',{extend:'Ext.Component',requires:['Ext.util.MixedCollection'],errorIconCls:'x-status-error',errorListCls:'x-status-error-list',validIconCls:'x-status-valid',showText:'The form has errors (click for details...)',hideText:'Click again to hide the error list',submitText:'Saving...',init:function(sb){sb.on('render',function(){this.statusBar=sb;this.monitor=true;this.errors=Ext.create('Ext.util.MixedCollection');this.listAlign=(sb.statusAlign==='right'?'br-tr?':'bl-tl?');if(this.form){this.formPanel=Ext.getCmp(this.form);this.basicForm=this.formPanel.getForm();this.startMonitoring();this.basicForm.on('beforeaction',function(f,action){if(action.type==='submit'){this.monitor=false;}},this);var startMonitor=function(){this.monitor=true;};this.basicForm.on('actioncomplete',startMonitor,this);this.basicForm.on('actionfailed',startMonitor,this);}},this,{single:true});sb.on({scope:this,afterlayout:{single:true,fn:function(){sb.statusEl.getEl().on('click',this.onStatusClick,this,{buffer:200});}},beforedestroy:{single:true,fn:this.onDestroy}});},startMonitoring:function(){this.basicForm.getFields().each(function(f){f.on('validitychange',this.onFieldValidation,this);},this);},stopMonitoring:function(){this.basicForm.getFields().each(function(f){f.un('validitychange',this.onFieldValidation,this);},this);},onDestroy:function(){this.stopMonitoring();this.statusBar.statusEl.un('click',this.onStatusClick,this);this.callParent(arguments);},onFieldValidation:function(f,isValid){if(!this.monitor){return false;}
var msg=f.getErrors()[0];if(msg){this.errors.add(f.id,{field:f,msg:msg});}else{this.errors.removeAtKey(f.id);}
this.updateErrorList();if(this.errors.getCount()>0){if(this.statusBar.getText()!==this.showText){this.statusBar.statusEl.removeCls(["x-status-base-valid-icon",this.validIconCls]);this.statusBar.setStatus({text:this.showText,iconCls:"x-statusbar-base-error-icon "+this.errorIconCls});}}else{this.statusBar.statusEl.removeCls(["x-statusbar-base-error-icon",this.errorIconCls]);this.statusBar.clearStatus().setIcon("x-status-base-valid-icon "+this.validIconCls);}},updateErrorList:function(){if(this.errors.getCount()>0){var msg='<ul>';this.errors.each(function(err){msg+=('<li id="x-err-'+err.field.id+'"><a href="#">'+err.msg+'</a></li>');},this);this.getMsgEl().update(msg+'</ul>');}else{this.getMsgEl().update('');}
this.getMsgEl().setSize('auto','auto');},getMsgEl:function(){if(!this.msgEl){this.msgEl=Ext.DomHelper.append(Ext.getBody(),{cls:this.errorListCls},true);this.msgEl.hide();this.msgEl.on('click',function(e){var t=e.getTarget('li',10,true);if(t){Ext.getCmp(t.id.split('x-err-')[1]).focus();this.hideErrors();}},this,{stopEvent:true});}
return this.msgEl;},showErrors:function(){this.updateErrorList();this.getMsgEl().alignTo(this.statusBar.getEl(),this.listAlign).slideIn('b',{duration:300,easing:'easeOut'});this.statusBar.setText(this.hideText);this.formPanel.el.on('click',this.hideErrors,this,{single:true});},hideErrors:function(){var el=this.getMsgEl();if(el.isVisible()){el.slideOut('b',{duration:300,easing:'easeIn'});this.statusBar.setText(this.showText);}
this.formPanel.el.un('click',this.hideErrors,this);},onStatusClick:function(){if(this.getMsgEl().isVisible()){this.hideErrors();}else if(this.errors.getCount()>0){this.showErrors();}}});
